version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - 123str_planner

  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - 123str_planner

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 123str_planner
    volumes:
      - mongo-data:/data/db

networks:
  123str_planner:
    driver: bridge

volumes:
  mongo-data:
    driver: local
