import { IProject } from "./interface/IProject";

export const ProjectExample: IProject[] = [
  {
    DOSSIER: "22.01.609U",
    AFFAIRE: "(PT) test IGC",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX",
    "LIVR. (tri)": "0000-00-00",
    AGENCE: "Anglet (64)",
    CLIENT: "I.G.C.",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
    "HONOS (EUR HT)": "",
  },
  {
    DOSSIER: "22.01.609U",
    AFFAIRE: "(PT) Maisons Alpes Savoie",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX",
    "LIVR. (tri)": "0000-00-00",
    AGENCE: "Anglet (64)",
    CLIENT: "Maisons Alpes Savoie",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
    "HONOS (EUR HT)": "",
  },
  {
    DOSSIER: "22.01.609U",
    AFFAIRE: "Propriété AZERTY",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX",
    "LIVR. (tri)": "0000-00-00",
    AGENCE: "Anglet (64)",
    CLIENT: "",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
    "HONOS (EUR HT)": "",
  },
  {
    DOSSIER: "22.01.609U",
    AFFAIRE: "Propriété M. LE TARGAT et Mme KHATIB-BRUNET",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX",
    "LIVR. (tri)": "0000-00-00",
    AGENCE: "Anglet (64)",
    CLIENT: "",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
    "HONOS (EUR HT)": "",
  },
  {
    DOSSIER: "22.05.139Y",
    AFFAIRE: "SCI BJL FAMILY - Propriété M. JOUIS",
    CLIENT: "SCI BJL FAMILY - M. JOUIS",
    ARCHITECTE: "ADENOV",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX, Thomas GALLET",
    "LIVR. (tri)": "0000-00-00",
    "HONOS (EUR HT)": "1250",
    AGENCE: "Villefranche-sur-Saône (69)",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
  },
  {
    DOSSIER: "22.01.089L",
    AFFAIRE: "CONSTRUCTION D'UN BATIMENT 4 - Tranche 2",
    CLIENT: "OBJECTIF PIERRE",
    "AGENCE LIVREE": false,
    RESSOURCES: "Guillaume NESME, Vanessa LAFRECHOUX, Eudes MARCHAND",
    "LIVR. (tri)": "0000-00-00",
    "TEMPS REALISE": "2.5",
    "HONOS (EUR HT)": "5950",
    AGENCE: "Clisson (44)",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS RESTANT": "",
  },
  {
    DOSSIER: "22.01.109L",
    AFFAIRE: "Propriété M. et Mme BERNARD (Mansard)",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX",
    "LIVR. (tri)": "0000-00-00",
    AGENCE: "Clisson (44)",
    CLIENT: "",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
    "HONOS (EUR HT)": "",
  },
  {
    DOSSIER: "22.01.013L",
    AFFAIRE: "CAPELLI GROUPE - 40 LOGEMENTS",
    CLIENT: "SCCV ARENTHON VERGERS",
    "AGENCE LIVREE": false,
    RESSOURCES:
      "Vanessa LAFRECHOUX, Guillaume NESME, Thomas GALLET, Eudes MARCHAND",
    "LIVR. (tri)": "0000-00-00",
    "TEMPS REALISE": "35",
    "HONOS (EUR HT)": "15000",
    AGENCE: "Clisson (44)",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS RESTANT": "",
  },
  {
    DOSSIER: "22.01.199L",
    AFFAIRE: "Propriété M. BERTHAUD - Percement",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX",
    "LIVR. (tri)": "0000-00-00",
    AGENCE: "Clisson (44)",
    CLIENT: "",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
    "HONOS (EUR HT)": "",
  },
  {
    DOSSIER: "22.01.209L",
    AFFAIRE: "Propriété M. KARAKUS",
    "AGENCE LIVREE": false,
    RESSOURCES: "Vanessa LAFRECHOUX",
    "LIVR. (tri)": "0000-00-00",
    AGENCE: "Clisson (44)",
    CLIENT: "",
    ARCHITECTE: "",
    SOL: "",
    LIVRAISON: "",
    LIVRTRI: "0000-00-00",
    "TEMPS PREVU": "",
    "TEMPS REALISE": "",
    "TEMPS RESTANT": "",
    "HONOS (EUR HT)": "",
  },
];
