export const ProjectParameters = [
  "DOSSIER",
  "AFFAIRE",
  "CLIENT",
  "ARCHITECTE",
  "AGENCE LIVREE",
  "RESSOURCES",
  "SOL",
  "LIVRAISON",
  "LIVR. (tri)",
  "TEMPS PREVU",
  "TEMPS REALISE",
  "TEMPS RESTANT",
  "HONOS (EUR HT)",
];